
theme="base16_terminal"

[editor]
bufferline='multiple'
line-number='relative'

[editor.indent-guides]
render = true
character = "│"

[keys.normal]
A-j=["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k=["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
x = "extend_line"
X = ["goto_first_nonwhitespace", "extend_to_line_end"]
V = ["ensure_selections_forward", "extend_to_line_end"]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
tab = ":buffer-next"
S-tab = ":buffer-previous"
Q = ":noop"
A-q = "record_macro"
C-q = ":bclose"


